version: '3'

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: abcdef
      POSTGRES_USER: dbuser
      POSTGRES_DB: app-db
    volumes:
      - "./dbdata:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  
  # browser client
  db-admin:
    image: adminer:latest
    ports:
      - 8080:8080
